/* This file will be used to test how comments work */

/*
*
* Block Comment C/C++ Style
*
*/

// Single line C/C++ style

# Single line assembly style

@ Single line assembly style some assembly lauguages

addi    r0, /* Use stack point */ r1

li      r0, 0x450   # After instruction

cmp     r5, r6  // After instruction

subf     r0, // Some comment r2

# this is not valid asm  (why is it here?)
mulli   r2, #Some comment r6

/*

add 

.section
*/

.include
.bss
.text
.data
.rodata
.sdata
.sdata2
.note "shits"
.org
.section ".shits"
.previous
.error "sefsef"
.ident
.need
.vle
.novle
.warning "sefse"
.nowarning
.set
.weak
.extern
.global Trolled
.globl Trolled2
.align
.ascii
.asciz
.balign
.byte
.double
.float
.long
.short
.space
.file
.fsize
.scall
.size
.type
.eject
.gen
.nogen
.list
.nolist
.title
.subtitle
.sbttl
.rept
.endr
.macro
.macrodef
.endm
.exitm
.strz
.skip
.offset
.comm
.lcomm
.lsbss
.sbss
.dsect
.end
.equ
.inspect "file.h"
.if 1
.elseif
.else
.endif

// add

# add

#invalid thing so is valid comment too apparently

#ifdef 
